### 사용자 등록
POST http://localhost:8081/members
Content-Type: application/json

{
  "email": "seok@gmail.com",
  "password": "1234",
  "name": "seokrae"
}

### 로그인
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "email": "seok@gmail.com",
  "password": "1234"
}

### 사용자 수정
PUT http://localhost:8081/members/1
jwt-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic2Vva3JhZSIsImVtYWlsIjoic2Vva0BnbWFpbC5jb20iLCJpc3MiOiJqd3QtcmVkaXMtc2VydmljZSIsInN1YiI6Imp3dC1zZXJ2aWNlIiwiYXVkIjoic2VvayIsImlhdCI6MTYyODM0MzQyMSwiZXhwIjoxNjI4MzQzNDIxfQ.IxjXMQHAFJRFU6GUuPW-zss-bQlAw0qhMCLmMXBwCCs
jwt-refresh-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoic2Vva3JhZSIsImVtYWlsIjoic2Vva0BnbWFpbC5jb20iLCJpc3MiOiJqd3QtcmVkaXMtc2VydmljZSIsInN1YiI6Imp3dC1zZXJ2aWNlIiwiYXVkIjoic2VvayIsImlhdCI6MTYyODM0MzQyMiwiZXhwIjoxNjI4MzQzNzIyfQ.0lwN1Wksu92_ZaCa1zWxciP5OVaW2UVPSHaW5bJXw_c
Content-Type: application/json

{
  "email": "seok@gmail.com",
  "password": "1234",
  "name": "seokrae"
}


### 사용자 삭제

DELETE http://localhost:8081/members/1
Content-Type: application/json

{
  "password": "1234",
  "name": "seok"
}
